import {Dimensions, StyleSheet} from 'react-native';
import { FontFamily, FontSizes, ThemeColors } from '../../../../../theme/globalStyles';

const {width, height} = Dimensions.get("window")

const styles = StyleSheet.create({
    screen: {
        flex: 1,
        backgroundColor: "#FFFFFF",
      },
      view:{
        flexDirection:"row",
        alignItems:"center",
        justifyContent:"space-between",
        marginBottom:30
      },
      viewContainer:{
        paddingHorizontal:35,
        backgroundColor:"white",
        elevation:5,
        paddingVertical:35,
        paddingBottom:20
      },
      heading:{
        fontFamily:FontFamily.primaryBold,
        fontSize:FontSizes.hugeSS,
        color:ThemeColors.textPrimary
      },
      search:{
        borderWidth:1,
        borderColor:"#DBD9D1",
        borderRadius:10,
        paddingHorizontal:10,
        flexDirection:"row",
        alignItems:"center",
        justifyContent:"space-between"
      },
      searchInput:{
        fontFamily:FontFamily.secondaryRegular,
        color:ThemeColors.textSecondary,
        fontSize:FontSizes.normal,
        flex:1
      },
      view1:{
        marginTop:30
      },
      view2:{
        marginBottom:20,
        borderBottomColor:ThemeColors.textSecondary,
        borderBottomWidth:1,
        width:width,
        alignSelf:"center",
        paddingBottom:15,
        paddingHorizontal:35,
      },
      container:{
        flexDirection:"row",
        alignItems:"flex-start",
        justifyContent:"space-between",
        marginBottom:20,
        paddingHorizontal:35
      },
      content:{
        flexDirection:"row",
        alignItems:"center"
      },
      contentText:{
        fontFamily:FontFamily.primaryBold,
        fontSize:FontSizes.largeX,
        color:ThemeColors.textPrimary,
        marginLeft:10
      },
      logo:{
        backgroundColor:ThemeColors.primary,
        borderRadius:6,
        padding:10,
        paddingHorizontal:13
      },
      modal:{
        backgroundColor:"white",
        flexDirection:"row",
        alignItems:"center",
        paddingHorizontal:35,
        paddingBottom:20
      },
      modalContent:{
        alignItems:"center",
        marginRight:40
      },
      text:{
        fontFamily:FontFamily.primaryMedium,
        fontSize:FontSizes.normal,
        color:ThemeColors.textPrimary,
        marginTop:7
      },
      primaryButton:{
        position:"absolute",
        backgroundColor:ThemeColors.primary,
        padding:20,
        borderRadius:16,
        alignItems:"center",
        bottom:"3%",
        right:"5%"
      },
      box:{
        flexDirection:"row",
        alignItems:"center",
        padding:10,
        justifyContent:"space-between",
        borderBottomWidth:1,
        borderBottomColor:"#DBD9D1",
        paddingHorizontal:35
      },
      boxContainer:{
        flexDirection:"row",
        alignItems:"flex-start",
      },
      boxImage:{
        resizeMode:"contain",
        width:50,
        height:50
      },
      boxTextContainer:{
        flexDirection:"row",
        alignItems:"flex-start",
        marginLeft:10
      },
      boxText:{
        fontFamily:FontFamily.primaryBold,
        fontSize:FontSizes.largeX,
        color:ThemeColors.textPrimary,
        marginRight:12,
        maxWidth:150
      },
      boxText1:{
        fontFamily:FontFamily.secondaryRegular,
        fontSize:FontSizes.normal,
        color:"#94928C",
        maxWidth:150
      },
      view3:{
        backgroundColor:ThemeColors.primary,
        borderRadius:6,
        padding:5
      },
      boxText2:{
        fontFamily:FontFamily.secondaryBold,
        fontSize:FontSizes.tiny,
        color:ThemeColors.textPrimary
      },
      view4:{
        backgroundColor:"#FFFFFF",
        width:"100%",
        alignItems:"center",
        borderBottomColor:"#DBD9D1",
        borderBottomWidth:1,
        paddingTop:20
      },
      view5:{
        width:"100%",
        paddingHorizontal:35
      },
      view6:{
        width:"100%",
        borderTopColor:"#DBD9D1",
        borderTopWidth:1,
        padding:20
      },
      container1:{
        flexDirection:"row",
        alignItems:"flex-start",
        justifyContent:"space-between",
        width:"100%"
      },
      container2:{
        flexDirection:"row",
        alignItems:"center"
      },
      container2Text:{
        fontFamily:FontFamily.secondaryBold,
        fontSize:FontSizes.normal,
        color:ThemeColors.textPrimary,
        marginRight:8
      },
      container3Text:{
        fontFamily:FontFamily.secondaryBold,
        fontSize:FontSizes.tiny,
        color:"#BBBAB3",
        marginRight:20
      },
      container4:{
        marginTop:20,
        flexDirection:"row",
        alignItems:"flex-start",
        width:"100%"
      },
      container5:{
        marginRight:20
      },
      container5Heading:{
        fontFamily:FontFamily.secondaryBold,
        fontSize:FontSizes.tiny,
        color:"#BBBAB3"
      },
      container6:{
        flexDirection:"row",
        alignItems:"center"
      },
      container6Heading:{
        fontFamily:FontFamily.secondaryBold,
        fontSize:FontSizes.smallX,
        color:ThemeColors.textPrimary,
        marginRight:14
      },
      container7:{
        marginTop:20,
        flexDirection:"row",
        alignItems:"center",
        justifyContent:"center",
        width:"100%",
        marginBottom:15
      },
      button:{
        backgroundColor:ThemeColors.primary,
        padding:10,
        paddingHorizontal:20,
        alignItems:"center",
        borderRadius:50,
        marginRight:10,
        alignSelf:"center"
      },
      buttonText:{
        fontSize:FontSizes.large,
        fontFamily:FontFamily.primaryBold,
        color:ThemeColors.textPrimary
      }
})

export default styles;